version: "3.2"

services:
  komiser:
    image: tailwarden/komiser:3.0.16
    restart: always
    platform: linux/amd64
    command: "--config /usr/bin/config.toml"
    volumes:
      - $PWD/config.toml:/usr/bin/config.toml
    ports:
      - 3000:3000